### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by nturaga** [nturaga/bioc-galaxy-jupyter-notebook#1]
- [x] Merge upstream updates to feature branch.
- [x] Email people on the names list to notify Oct 13th deadline
- [x] Update bioconductor_skeleton.py file with changes.
- [x] Fix bugs, in branch `add_bioc_features`
- [ ] Make Jupyter Notebook (@malloryfreeberg)
- [x] Make toy example instead of `motifbreakR` to help people follow along better. -- This becomes harder because the tool needs to be part of bioconductor and bioconda.  
- [x] Check updates in bioconductor_recipe.py from bioconda.

@malloryfreeberg Feel free to edit as needed.
